### ISSUE TITLE
Share Grafana Dashboard

### ISSUE THREAD

**Issue by Shinigami92** [Sleavely/satisfactory-savegame-prometheus-exporter#8]
Can you share your grafana dashboard?

<img src="https://camo.githubusercontent.com/9acee013def2457766c0c7b04228fa8917c3bc9f053b417eac1fc39370f923fd/68747470733a2f2f692e696d6775722e636f6d2f66446a5a5936472e706e67"/>

**Comment by Sleavely** [comment]
Good idea! Solved in 25fb6cc

**Comment by Shinigami92** [comment]
Awesome 🤩 works 🚀 

![image](https://github.com/user-attachments/assets/8654001f-f102-49b1-89bb-2f27e9eb5184)

_my server is currently not running, so that's why no "api" data_
